language: node_js
node_js:
  - "4.0.0"
sudo: false
script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm lint
  - npm test:node
  - npm test:coveralls
  - npm test:saucelabs
