language: node_js
node_js:
  - "6.0.0"
sudo: false
script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run lint
  - npm run test:node
  - npm run test:coveralls
  - npm run test:saucelabs
